### ISSUE TITLE
선생님 컴파일을 어떻게 하는지 모르겠습니다ㅠㅠ

### ISSUE THREAD

**Issue by ACDRv0330** [Not-swasd/classcard-hack#1]
제곧네입니다. 코딩 초보라 어떻게 하는지 검색해도 모두 소스코드처럼 나와 진행할 수 없더군요... 디스코드에 봇을 어떻게 추가하는지 도와주셨으면 합니다...

**Comment by Not-swasd** [comment]
이슈의 용도가 그런 용도는 아닌걸로 알고있습니다.
그런건 본인이 알아서 찾아보세요.
