### ISSUE TITLE
컴파일 과정 중에 오류 있어요

### ISSUE THREAD

**Issue by kekidev** [Not-swasd/classcard-hack#2]
tsconfig.json이랑 package.json 업데이트 부탁드려요 ❤️❤️

**Comment by Not-swasd** [comment]
무슨 오류인지 정확히 기재해주세요

**Comment by kekidev** [comment]
<img width="1920" alt="스크린샷 2022-08-16 오후 6 04 12" src="https://user-images.githubusercontent.com/72121955/184841552-810b071d-4b0b-4bf6-afce-9045e72d8514.png">
